;; -*- mode: eask; lexical-binding: t -*-

(package "mlua-mode"
         "0.1.0"
         "Major mode for mLua")

(website-url "https://github.com/MSW-cmty/mlua-mode")
(keywords "languages")

(package-file "mlua-mode.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)

(depends-on "emacs" "26.1")
(depends-on "lua-mode")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
